### ISSUE TITLE
View not present in JSON response from DAC

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/SdkSearch#101]
* [ ] file bug somewhere about this

**Comment by davidkraus** [comment]
Cool Project, learned a lot looking through the code.

android.view.View (if I'm not completely blind) is not explicitly listed in the server response (only the subclasses of android.view.View). 
Checked out Roman's extension and it is listing android.view.View. Hadn't time to look further into it - hope this helps somehow.

**Comment by JakeWharton** [comment]
Hah! You're right. I guess i'll have to figure out where to send that bug tomorrow...

Roman's uses an old source that no longer exists. And actually since then he's merged in a listing that is produced by this project that will also lack `View`.

**Comment by JakeWharton** [comment]
Fixed by #156's fix.
