### ISSUE TITLE
Search results don't load after screen rotation

### ISSUE THREAD

**Issue by SamThompson** [JakeWharton/SdkSearch#104]
We're only storing the presenter job for the first presenter that we inject and call `start` for. When `onCreate` is called again, we inject a new instance of the presenter, but the `Job` stays the same. Later on when we call `for (model in presenter.models)`, we're iterating over the models emitted by the newly injected presenter. Since we've never started that presenter, it won't emit values.

Maybe we could scope the presenter such that the same instance is injected each time?

**Comment by JakeWharton** [comment]
Ah, are you on `master`? I did recently remove the scoping with an intent to actually pass the presenter instance through the non-config object of the activity on rotation. But I didn't do that...

For now the scope should probably just be restored.

**Comment by JakeWharton** [comment]
Are you building yourself or using the "Update from CI" launcher shortcut?

**Comment by JakeWharton** [comment]
5bf0c6ad2608ea97e67a956aa18d549a38c2f7ad
