### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [JakeWharton/SdkSearch#105]
Hi,

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

**Comment by JakeWharton** [comment]
I don't have any plans to add the app to app stores other than the Play Store at this time. And I'm not sure I want to preclude myself from adding non-OSS libraries in the future. For example, analytics would be a nice addition in the future and most of those SDKs are closed source.
