### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by maaudrana** [JakeWharton/SdkSearch#106]
Hall0 @JakeWharton 
Interesting about your this projects.i am a designer want to make a logo for this projects if you have any requirements then let me know.its free for any open source projects 
Thank you

**Comment by JakeWharton** [comment]
A logo was already contributed by a designer which I'm quite happy with, so I don't need a new one designed at this time. You can find it here: https://github.com/JakeWharton/SdkSearch/tree/master/art. Thanks for offering, though!

**Comment by maaudrana** [comment]
its ok
