### ISSUE TITLE
Optionally suppress support library classes

### ISSUE THREAD

**Issue by jameswald** [JakeWharton/SdkSearch#111]
When using AndroidX the old support library classes are essentially fake news. Could we suppress them with an optional toggle? To do this reliably the app might download and parse `androidx-class-mapping.csv` from https://developer.android.com/topic/libraries/support-library/refactor.

Alternatively the search results could be presented in a fancier consolidated format where the three classes are collapsed together with separate affordances for platform, support, and AndroidX. It may not be feasible to collapse platform classes without a canonical mapping between those and support / AndroidX.

**Comment by JakeWharton** [comment]
I'm not a big fan of options. Let me ask around and see how long we plan to return them in the search results. I'd rather see the docs updated so that the androidx versions point to the dejetified versions but they don't show up in search results.

**Comment by orionlee** [comment]
I echo @jameswald 's sentiment. It'd be great if it can be tweaked so that the "preferred" results are more accessible. E.g., assuming `androidx` is the preferred one, I hope the app would  
- reorder so that `androidx` classes show up on top, followed up platform, then support, or
- filter out so that support (or even platform).

A screenshot (of current behavior), to help to visualize desirable result:
![image](https://user-images.githubusercontent.com/250644/50466936-2179a080-0955-11e9-8093-28af201e6c57.png)

**Comment by JakeWharton** [comment]
Yeah let's fix this in sort for now.

**Comment by JakeWharton** [comment]
I have removed them from the next version. Let's see if anyone complains 😀 .

**Comment by orionlee** [comment]
As one vote, I work on some projects use androidx, while some others still use android support library: so I have some reservation on outright removal of support library.

**Comment by JakeWharton** [comment]
Is there a meaningful difference to visiting the documentation for the support library type instead of the AndroidX type? Both types are created from the same source file so there should be no functional difference nor difference in documentation.

**Comment by orionlee** [comment]
@JakeWharton I always assume that while support and Androidx start out the same, at some point I'll start to see methods / classes that are in Androidx only.

From what you suggest, they are still the same (and will stay the same for sometime), then there is no reason to visit support library doc.

**Comment by JakeWharton** [comment]
Well that's a decent point. Now with the betas there are new APIs being
added.

**Comment by orionlee** [comment]
I just came across an AndroidX-only class while working on a project using the old support library:

https://developer.android.com/reference/androidx/test/core/app/ApplicationProvider
