### ISSUE TITLE
View source link includes URL fragment

### ISSUE THREAD

**Issue by hongrich** [JakeWharton/SdkSearch#114]
The Chrome extension adds a 'view source' link to the class reference pages, but it doesn't seem to be stripping out URL fragments (and maybe other URL components as well?).

* Navigate to https://developer.android.com/reference/android/widget/Toolbar#collapseActionView()

* 'view source' links to https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/Toolbar#collapseActionView().java

* 'view source' should link to https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/widget/Toolbar.java

**Comment by JakeWharton** [comment]
Apparently node.js doesn't let me use `URL` without `require('url')` which you don't need when running in a browser. As a result I've spent 100x longer trying to get the tests working than fixing the bug and writing the tests. Ugh. 🤦‍♂️
