### ISSUE TITLE
Chrome extension does not add "view source" button on Android doc

### ISSUE THREAD

**Issue by jschmid** [JakeWharton/SdkSearch#117]
I don't know how much is copied/forked from Roman Nurik's extension. But your Chrome extension listing says:

> 2. Adds a 'view source' link next to the SDK class name for class reference pages on developer.android.com. Clicking this link navigates to the relevant source file on android.googlesource.com.

And for me it does not work. It does on Roman's extension.

Is this a bug, a missing feature?

**Comment by JakeWharton** [comment]
Can you post a screenshot? It's working for me. Here's a screenshot of it that's used for the Chrome listing: https://github.com/JakeWharton/SdkSearch/blob/master/frontend/chrome-extension/store/screenshots/2.png

**Comment by jschmid** [comment]
Sorry my bad. Roman's extension put a big bordered button on the page, and yours is too well integrated in it. I missed it.
Thanks!
