### ISSUE TITLE
Question: How can this project work without jetifier?

### ISSUE THREAD

**Issue by ursusursus** [JakeWharton/SdkSearch#151]
Hi, quick question, from gradle.properties it seems you are not using jetifier. However, you are including dagger-android 2.19, which has dependency on the old package support-annotations.

```
+--- com.google.dagger:dagger-android:2.19
|    +--- com.google.dagger:dagger:2.19 (*)
|    +--- com.android.support:support-annotations:25.0.0 -> 26.1.0
|    \--- javax.inject:javax.inject:1

```
How come?

**Comment by JakeWharton** [comment]
It doesn't use any old dependencies

**Comment by JakeWharton** [comment]
The annotations are just double packaged in the old namespace and the new one.
