### ISSUE TITLE
Why is org.gradle.parallel=true not specified?

### ISSUE THREAD

**Issue by ursusursus** [JakeWharton/SdkSearch#152]
I had it that it is off by default, i.e. without org.gradle.parallel=true you wont get multithreaded builds in multimodule setup

**Comment by JakeWharton** [comment]
I tend to keep experimental features out of the checked-in `gradle.properties`. The CI script does specify this option and limits the workers to 2. My bash alias `gw` does also add `--parallel` to every command which further helps avoiding the need to check this in.

The primary reason to leave this out of all `gradle.properties` files is that for libraries you do not want to deploy artifacts in parallel.

I'm holding out for Gradle to one day have sane parallelism by default through workers.
