### ISSUE TITLE
Broken doc links to legacy support library

### ISSUE THREAD

**Issue by orionlee** [JakeWharton/SdkSearch#168]
Version: v1.4.0.0 Chrome extension on Chrome Web Store

The links to the documentation for legacy support library are missing `https://developer.android.com/` , leading to search page rather than the documentation.

Screenshots:

![image](https://user-images.githubusercontent.com/250644/55655836-1501b100-57aa-11e9-9ca6-c697af8cd3e4.png)

**Comment by JakeWharton** [comment]
Yeah I need to rev the data store version so these old entries are purged. The same thing happened on Android as well.

**Comment by JakeWharton** [comment]
Fixed by 8300e57390133e71ab08c04068515be2d58797ae

**Comment by JakeWharton** [comment]
And released to Play Store and Chrome Store as v1.4.1
