### ISSUE TITLE
Inclusion in FDroid

### ISSUE THREAD

**Issue by vanitasvitae** [JakeWharton/SdkSearch#175]
Hi!

Thank you very much for your work on the app!
I'd like to ask, if it is okay for you if I package SDK Search for the [FDroid](https://f-droid.org/) repository.
FDroid is a repository of applications that are licensed under a free software license. I missed SDK Search in there, so I decided to try to package it myself :)

I created an [inclusion request](https://gitlab.com/fdroid/fdroiddata/merge_requests/6012) with a metadata file, which allows the app to be build using FDroid build system.

I had to deactivate Bugsnag crash reporting though, as bugsnag requires the inclusion of API keys, which would violate FDroids [inclusion criteria](https://f-droid.org/docs/Inclusion_Policy/). 

Let me know if this change (see metadata/com.jakewharton.sdksearch/bugsnag.patch) and the general inclusion of SDK Search into FDroid is okay for you or if you have any objections.

**Comment by Apsaliya** [comment]
Related #105

**Comment by vanitasvitae** [comment]
As I understand #105, Mr. Wharton does not have plans to package SDK Search for FDroid himself, so my hope is that he may be okay with someone else doing the work for him :D

**Comment by JakeWharton** [comment]
The license of the project grants you the ability to build your own versions and modify the app without my consent provided you comply with it. But you can consider myself duly notified as per the requirements of FDroid.

To be clear, though, I am not maintaining this version nor will I be pushing updates to it.
