### ISSUE TITLE
SdkSearch extension doesn't index KDocs

### ISSUE THREAD

**Issue by ChrisCraik** [JakeWharton/SdkSearch#179]
For example, `ad<tab>BenchmarkState` shows no results,

But the docs are there: https://developer.android.com/reference/kotlin/androidx/benchmark/BenchmarkState

Same for any classes in Compose, presumably for the same reason.

**Comment by JakeWharton** [comment]
Deployed to production 🤞 . The Chrome extension only syncs on first open so you can restart Chrome to try. The app syncs on each open.

![Screen Shot 2020-03-02 at 4 44 11 PM](https://user-images.githubusercontent.com/66577/75720756-10d56080-5ca5-11ea-80a2-2044548e378a.png)

**Comment by ChrisCraik** [comment]
Verified it works after rebooting Chrome - Thanks!
