### ISSUE TITLE
Run this project in Android Studio

### ISSUE THREAD

**Issue by sempsmahad** [JakeWharton/SdkSearch#193]
### Questions
- Was this app developed in android studio, it is giving me several errors no matter my high computer specs and good internet?
- There are many random folders in the parent folder, is this an android project?

**Comment by JakeWharton** [comment]
I always use IntelliJ IDEA as Android Studio always lags behind on multiplatform support. But the project hasn't been touched in years, so it's unlikely to import without build changes to update to the latest of things. Google likes to break the data source and I got tired of dealing with it.

The folders are not random. The project is modularized. Each one has a specific purpose.

**Comment by DoozyDoz** [comment]
Thanks for the clarification @JakeWharton 👍, this was a nice idea but looks like google likes playing hide and seek, too bad
