### ISSUE TITLE
Chrome search dupe of Roman Nurik's SDK search?

### ISSUE THREAD

**Issue by lustigdev** [JakeWharton/SdkSearch#45]
https://chrome.google.com/webstore/detail/android-sdk-search/hgcbffeicehlpmgmnhnkjbjoldkfhoin?hl=en

I'm sure you were already aware of this but just wanted to figure out what the correlation was, if any.

**Comment by JakeWharton** [comment]
It will supersede it, yes.

**Comment by JakeWharton** [comment]
https://github.com/romannurik/AndroidSDKSearchExtension/issues/51#issuecomment-355196812
