### ISSUE TITLE
Try harder to disable keyboard suggestions.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/SdkSearch#57]
They still show up

**Comment by SimonMarquis** [comment]
Using `textVisiblePassword` seems to be a common workaround.  
Can you reproduce this bug on your devices using:

```java
android:inputType="textCapWords|textNoSuggestions|textVisiblePassword"
```

instead of

https://github.com/JakeWharton/SdkSearch/blob/142fe6f5f8fb184fbee19efd2451787f079e2a19/frontend/android/src/main/res/layout/main.xml#L38

**Comment by JakeWharton** [comment]
I had seen that suggestion, but I was trying to avoid it. I'm curious if it
causes any undesired behavior with password managers or the autofill
framework.

**Comment by JakeWharton** [comment]
I remember why I didn't leave textVisiblePassword in: it still shows the numbers on a separate line so you don't gain any space.

**Comment by JakeWharton** [comment]
No action to take, except complain loudly at GBoard for this stupid decision.
