### ISSUE TITLE
Use Kotlin Extensions for View Binding instead of findViewById

### ISSUE THREAD

**Issue by jaredsburrows** [JakeWharton/SdkSearch#61]
https://kotlinlang.org/docs/tutorials/android-plugin.html#view-binding

**Comment by JakeWharton** [comment]
These were intentionally not used and unless they alter code generation to be more like databinding I don't want to use them.

**Comment by jaredsburrows** [comment]
I believe it does, check out this blog here: https://antonioleiva.com/kotlin-android-extensions/.

**Comment by JakeWharton** [comment]
Databinding generates one type per layout with properties for the contained
views. Kotlin extensions generates top-level properties.

**Comment by blackvvine** [comment]
Hi, thank you for the awesome work in this library. I'm sorry to necrobump this thread, but I was hoping you could elaborate what is the drawbacks of the top-level properties approach used in Kotlin Android extensions.
