### ISSUE TITLE
A "return" might be missing on the following line

### ISSUE THREAD

**Issue by Zhuinden** [JakeWharton/SdkSearch#84]
https://github.com/JakeWharton/SdkSearch/blob/39a311c9ef2a1b7791c9810b55bacc538d238476/sync/src/main/java/com/jakewharton/sdksearch/sync/ItemSynchronizer.kt#L77

Just reading the code and noticed that it's probably supposed to `return` there.

**Comment by JakeWharton** [comment]
Seems like it, yes. Good eye.

**Comment by JakeWharton** [comment]
7836c10
