### ISSUE TITLE
[Suggestion] Make Search/EditText more user friendly

### ISSUE THREAD

**Issue by bernaferrari** [JakeWharton/SdkSearch#86]
I would like to suggest making the EditText's height here as _match_parent_:
https://github.com/JakeWharton/SdkSearch/blob/b145bc0321bcbac185d033276b63e0672f62eaad/search/ui/src/main/res/layout/main.xml#L33

I tested myself, it didn't change anything, since it has the attribute _center_vertical_.

Reasoning: The EditText is occupying the full toolbar, and there are be people (myself included) that will tap on the toolbar, in the area between the end of EditText and the end of the toolbar, expecting to show the keyboard. EditText's native size is not huge, so making it the size of the toolbar helps a lot.

**Comment by JakeWharton** [comment]
Makes sense. Want to send a PR?

**Comment by bernaferrari** [comment]
Done!
